### ISSUE TITLE
Add secure storage (enhancement)

### ISSUE THREAD

**Issue by realdmitchell** [arpitkh96/AmazeFileManager#109]
Great work. Would be nice to have a secure storage like CMFile manager.

**Comment by arpitkh96** [comment]
for what?

**Comment by lbdroid** [comment]
It seems to be for mounting a password protected loopback filesystem;
http://review.cyanogenmod.org/#/c/75739

I wouldn't put much priority into this, since Android is moving into maintaining a password protected encryption over the entire userdata partition, and further, everyone with even OLD versions of Android has this option via System Settings --> Security --> Encrypt Phone.

**Comment by lbdroid** [comment]
Whoa, hahahaha... its using password protected *ZIP* archives. This is NOT the correct way to implement this kind of function, since zip is not an RW filesystem.

**Comment by lbdroid** [comment]
Seems to be some kind of hack reimplementation of FUSE, and limited entirely to a few archive formats.
