### ISSUE TITLE
[feature-request] Gallery functionality implementable?

### ISSUE THREAD

**Issue by revuwa** [arpitkh96/AmazeFileManager#201]
I saw this commit: https://github.com/arpitkh96/AmazeFileManager/commit/cab30d0f09124201246f381e5842a184726dcc54 and wondered, if Amaze could be, (or already is) a simple gallery app replacement, too?
I mean just for viewing photos / pictures (probably swipable inside one folder or something like that).

Such a functionality could really great helping me:
* http://forum.xda-developers.com/general/general/request-modify-gallery2-app-t2873383

and/or the Replicant project:
* http://redmine.replicant.us/projects/replicant/wiki/Tasks

out.

**Comment by arpitkh96** [comment]
Nope it's not. And it's not worth adding an image viewer when each and every phone has inbuilt gallery

**Comment by okungnyo** [comment]
Agreed. Just be the best at what it already does as a file manager, and try not to do everything.

Case in point: ES File Explorer, which has basically become an OS top of an OS.

**Comment by pwendland** [comment]
I would definitely appreciate this functionality!

@arpitkh96: I like to have the same experience on phone and tablet. Using inbuilt gallery from vendor will not gurantee this. Furthermore, I don't like to have an separate app only for viewing pictures once  a month. Since QuickPic was bought by CM, this could be a killer feature for lots of people. And at last, I don't think, this will add much complexity to the app.

**Comment by lbdroid** [comment]
@revuwa what that commit does, is alters the intent sent to the gallery application so that it provides an album instead of just an image.

@pwendland That would be highly inappropriate. You have created an artificial distinction, the notion that a "separate application" would actually be any different than an integrated image viewer. This is nonsense, the file manager would have to implement additional classes to bring about this functionality, which are the classes provided by the image viewer application otherwise. If you require an image viewer, you should install an image viewer.

**Comment by arpitkh96** [comment]
Thanks lbdroid

**Comment by vishal0071** [comment]
I kind of agree with @pwendland here. You can see the in material design file manager CGI by Google in their guidelines, there's a file manager which actually opens an Image Viewer inbuit of it. It adds nice animations and matching accent colors to the app. Nice idea I guess.

**Comment by lbdroid** [comment]
Well, then you might as well just throw out Android altogether and rewrite everything yourself, since you seem to be hell bent on ultimately implementing every imaginable thing.

If you want to write an image viewer, do so. There is absolutely no purpose or advantage to building it into the file manager. Those visual things you mention do NOT depend on the two being tied into the same package.

And FYI: Good quality image viewers are not easy, or light. Go look at AOSP gallery source code.

**Comment by arpitkh96** [comment]
@lbdroid speaks from my side :D

**Comment by revuwa** [comment]
Thanks to everyone here for your answers and suggestions.

> Since QuickPic was bought by CM, this could be a killer feature for lots of people. And at last, I don't think, this will add much complexity to the app. (@pwendland)

I really hoped to see comments like this. For me, and/or the Replicant Project such a functionality would definitely be a 'killer feature'.

> If you want to write an image viewer, do so.
> And FYI: Good quality image viewers are not easy, or light. Go look at AOSP gallery source code. (@lbdroid)

While you're absolutely right, I personally doesn't have the skills to do that. That's the reason, why I opened a reward for that a long time ago, (my first link). If somebody reading this would be interested, and/or can give hints to get a simple open source picture/photo viewer app to work on Replicant (= Android 4.2.2 without 3D acceleration), I would be very happy to hear from you.

But it seems, my basic question is answered-, and can be closed now.

**Comment by vishal0071** [comment]
@revuwa don't reach on conclusions yet. I might contribute to it's development in my free time (:
