### ISSUE TITLE
Crash when going in background with "Back navigation" option enabled

### ISSUE THREAD

**Issue by steve95** [arpitkh96/AmazeFileManager#289]
Hi, Amaze crashes every time it goes in background (home button tap, open a file, etc), but only with the "Back navigation" option enabled.
I tried the last version and also the beta, on my phone (CM 5.1.1) and on my tablet (Android 4.4.2), and it happens every time exactly in the same way.

**Comment by Tony-il-Capo** [comment]
I also have this problem. When opening a file like videos or pictures, Amaze always crashes, after opening files android immediately pops up message like 'Amaze File Manger Stopped Working'.
I'm using a Sony Xperia S.

**Comment by vishal0071** [comment]
Any logcat?

**Comment by Tony-il-Capo** [comment]
Because of  other reasons I've reflashed my device and installed version 3.0.1(latest on F-Droid) of Amaze File Manager from F-Droid and it seems I don't have this problem anymore.
I'm almost sure that the problem still exists on latest 3.1.0 beta.

I don't have free time to test this and get the logcat, if someone have the time please get the logcat with the error. You can use an app on device to easily see the logcat. There's some on F-Droid.

**Comment by frafl** [comment]
I see the same error with the current version from FDroid and Playstore (i.e. 3.1.1).
Logcat says:
10-22 15:12:18.785 E/AndroidRuntime(...): Process: com.amaze.filemanager, PID: ...
10-22 15:12:18.785 E/AndroidRuntime(...): 	at com.amaze.filemanager.ui.Layoutelements.writeToParcel(Layoutelements.java:75)

**Comment by vishal0071** [comment]
Is been fixed, wait for new release.
