### ISSUE TITLE
Amaze 3.1.0 has been blocked from F-Droid

### ISSUE THREAD

**Issue by marmistrz** [arpitkh96/AmazeFileManager#313]
Reason: cluttered with jars. https://f-droid.org/wiki/page/com.amaze.filemanager

Maybe you could adapt it so that corresponding jars are built from source? There was a similar PR in the past but now there are many jars back

**Comment by vishal0071** [comment]
I tried adding maven repo for the dependencies in the past, but there were some compile time errors. 
Those dependencies are
ftplet-api-1.1.0-SNAPSHOT.jar
ftpserver-core-1.1.0-SNAPSHOT.jar

I'll try to find any workaround, so that fdroid can get the builds up.
For the time being, you can download fdroid specific builds from [here](https://www.androidfilehost.com/?w=files&flid=73985).

**Comment by Tony-il-Capo** [comment]
Please try to fix that, F-Droid is a must have for real free and and open source apps. It's much more convenient than using releases from here and much more easy to update.
Thanks.

**Comment by fxedel** [comment]
Current version 3.1.0 Beta 2 does work with F-Droid again :+1:
