### ISSUE TITLE
Request: APK shortcut

### ISSUE THREAD

**Issue by tribakzero** [arpitkh96/AmazeFileManager#322]
When I tap an APK icon on my home screen created by new shortcut feature, it sends me to amaze asking if I want to view the file or install it, allow me to tell amaze to directly install APK files, this could be an opt in setting.

**Comment by germanfr** [comment]
Also for all the files. Currently, a shortcut to a picture (for example) takes you to Amaze and then opens the image. Would be better to directly do the action instead of opening Amaze to do the action. 

ES file explorer does that. I uninstalled it for Amaze but the shortcuts I created still work. If I removed Amaze my shortcuts would stop working I think.
