### ISSUE TITLE
Can search results be sorted by relevance

### ISSUE THREAD

**Issue by LL12138LL** [arpitkh96/AmazeFileManager#3357]
**Is your feature request related to a problem? Please describe.**
When I search for some files with short names, I find it hard to find them because of too many search results

**Describe the solution you'd like**
Can search results be sorted by relevance

**Additional context**

https://user-images.githubusercontent.com/101189845/173608484-851993cd-12e1-4529-8a4e-15696c7f7233.mp4

**Comment by seelchen** [comment]
Hi, I would like to work on this.

My proposed sorting by relevance would be (from most to least important criteria):
1. Sort based on percentage matched. We would calculate how much of the name of a file is found in the search term (e.g. the search term "my" would match 20% in "my-cat.txt")
2. Prioritize files where the match is in the beginning of the name (e.g. with the search term "my", "my-cat.txt" would be prioritized before "rat-my.txt")
3. Prioritize files where the match could be a whole word in the file name (because it is separated with "-"/"_"/"."/space, e.g. with "my" as search term, "my-cat.txt" is prioritized before "mysterious")
4. Date modified

I also think than directories should not appear first in the search results but should be ranked with the same weight as files. 

It might also be helpful to be able to select which sorting should be applied, e.g. by relevance, by name, by date modified etc.

**Comment by VishnuSanal** [comment]
@seelchen hi, great to see that you are interested in working on Amaze. there's a new search technique being implemented in #3730. please see [this](https://github.com/orgs/TeamAmaze/discussions/3984) discussion for more details. let's discuss this new behavior before you start working on it.

**Comment by seelchen** [comment]
Hi, thank you for the pointers!
I looked at the new search technique and it seems like the results are displayed in the order in which they are loaded in [`ListFileCommand#listFiles`](https://github.com/TeamAmaze/AmazeFileManager/blob/release/4.0/app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt#L46) (which doesn't explicitly give any guarantees about the order). The old search is also used as `DeepSearch`. I think that sorting by relevance could improve the usability for all three search modes.

**Comment by seelchen** [comment]
My plan is to reuse the `FileListSorter` to sort both `LayoutElementParcables` (used in old search) and `HybridFileParcelables` (used in new search). I would need make them both implement a new interface to access the information needed for sorting. The sorting would be done after all items are found.
