### ISSUE TITLE
What's the historical reason of `supportOldLangCodes` Gradle task?

### ISSUE THREAD

**Issue by trietbui85** [arpitkh96/AmazeFileManager#4217]
https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/build.gradle#L279
```
tasks.register('supportOldLangCodes')

[['id', 'in'], ['yi', 'ji'], ['he', 'iw']].forEach { sourceCode, destinationCode ->
    def copyTask = tasks.create('copyStrings' + sourceCode + 'Into' + destinationCode, Copy) {
        description('copying values-' + sourceCode + ' strings into values-' + destinationCode)
        from('src/main/res/values-' + sourceCode)
        into('src/main/res/values-' + destinationCode)
        include('strings.xml')
    }
    supportOldLangCodes.dependsOn copyTask
}
```
There is Gradle task `supportOldLangCodes` but I don't understand why we must copy String resource files to other languages.
Could you add some inline comments to this task for explaining please? 🙏

**Comment by EmmanuelMess** [comment]
The language codes produced by Transifex, the web tool we use to translate, creates files for languages, identified by a language code. The problem is that for some languages the codes changed, and android uses the old codes, but Transifex the new ones, so for compatibility this step copies the files to the old codes. I think newer android versions support both language codes though.

See #1790
