### ISSUE TITLE
File selection issue

### ISSUE THREAD

**Issue by axet** [arpitkh96/AmazeFileManager#505]
Simple issue with long list folders:

select few files, scroll up and accident refresh view - selection will drop

**Comment by vishal0071** [comment]
This is the expected outcome. What's there to fix?

**Comment by vishal0071** [comment]
Consult explanation in #506

**Comment by axet** [comment]
I start select files, then I found out here not all files present in the FileManager. I have to scroll up, because here is a lot of files, make 10 finger scroll up, then I pull down folder and refresh happend. I scroll back 10 slides down to get to the end of file list  and find out selection were reset.

Seems like a very bad design. I did 20 click and lost them all!

**Comment by vishal0071** [comment]
I know it's annoying but you'll get used to it.
For eg, instead of scrolling up marginally, scroll up with a fling, which will leave you to the top of the list and won't refresh the list. If you want to scroll marginally then just keep a track on the handle to the right, if it is almost at top, try not to scroll down too much so that you know when you're actually pulling to refresh.
It just take a little getting use to.

**Comment by Alexander--** [comment]
@vishal0071 Could you please remove the pull-to-refresh system completely? It is poorly fit for user-editable lists (such as filesystem contents), and there is a vastly superior approach — just use [inotify](https://developer.android.com/reference/android/os/FileObserver.html) to refresh list automatically when directory contents change.

**Comment by vishal0071** [comment]
Alright, custom File observer is a thing now, so I guess we're resolved here.
