### ISSUE TITLE
Can't open text/xml files from /data/data/*

### ISSUE THREAD

**Issue by pejakm** [arpitkh96/AmazeFileManager#65]
I cannot open any of the configuration files from */data/data/**, except for files under `/data/data/com.amaze.filemanager`. Error report is just: "Error". I guess this could be due to file permissions.

Note: root access is enabled, and I can open text/xml files under /system, for example.

**Comment by arpitkh96** [comment]
OK i will implement it... Though it's obvious that files aren't readable in /data that's why permissions needs to be altered

**Comment by pejakm** [comment]
Commit 1c477062b473e64682e2b59d1031963455858023 solves this by chmoding files to 777 and leaves them that way. I'm not an expert, but I think this is not the right way to do it. I just tested CyanogenMod File Manager, and like I've said before, it can open files from /data (given that it has root access), but it doesn't modify any file permissions.

**Comment by vishal0071** [comment]
I'll look into the possible solution later...

**Comment by ShadowKyogre** [comment]
@vishal0071: I think this commit from CM File Manager might help with implementing it without modifying the permissions:

https://github.com/CyanogenMod/android_packages_apps_CMFileManager/commit/3d75aa843f6638564d29862f300a6e8755cb9ea2
https://github.com/CyanogenMod/android_packages_apps_CMFileManager/commit/14d3354a9d712e1c53b793e7bbdf35dd9bb327bc

In short, what CM File manager is doing is running ```cat``` with root permissions to extract the contents of the file for viewing in the text editor. It then writes this back using ```dd``` (again, with root permissions) to the output file. It also tries to make sure that dd writes exactly the information inputted by the user into the file (it tries again if the operation didn't write exactly what the user inputted). I'm pretty sure there is a way to do the writing without dd, but I'm not sure how to do that yet either.

**Comment by arpitkh96** [comment]
you mean we should copy files in cache and then read it?that doesnt seems a good idea either.

**Comment by ShadowKyogre** [comment]
@arpitkh96: Yeah, the copy-into-cache doesn't seem like a good idea either if we're avoiding the use of ```dd```. The main reason I didn't want to suggest using ```dd``` was because I was looking at the library you were using for root access, but wasn't sure where we'd pipe the file as stdin for dd so dd has data to work with. Otherwise, I'd totally be for it.

**Comment by arpitkh96** [comment]
So what do you think is the best idea.... Changing permissions could be deadly

**Comment by ShadowKyogre** [comment]
@arpitkh96 : I think I have an idea after looking at how OpenExplorer does it too, which uses the same library as AmazeFileManager to access root files: https://github.com/BrandroidTools/OpenExplorer/blob/50489177d1176518d9a9c626674b5c2e3c7e3f7f/src/org/brandroid/openmanager/data/OpenFileRoot.java#L499-L502

For getting file contents, use cat as root on the file that needs to be read and take that output (which is how Cyanogenmod's file manager does it, OpenExplorer puts the file in a tmp cache).

For writing the file contents, use cat as root with a command similar to the highlighted lines to redirect the output to the appropriate file.

**Comment by arpitkh96** [comment]
i didnt fully got your idea. how does cat preserves permissions,for example in this case...openexplorer is using external storage for its temp file.and obviously if he copies the file in external memory(or internal,but not system) the permissions will not be preserved.So how the permissions are preserved using this way.the only way i see is manually setting permissions later

**Comment by ShadowKyogre** [comment]
For reading from a file, cat just puts the contents of the file into 
stdout, which can be retrieved from the RootTools library by doing 
something like this in the link: 
https://github.com/Stericson/RootTools/wiki/Usage#running-root-commands 
(it's on a per-line basis, so one may need concatenate the lines).

For writing to a file, putting data into a file using cat by redirecting 
the output to the doesn't modify the file permissions. OpenExplorer 
doesn't copy the file from the tmp to *write* to it, just for *reading* 
it (most likely because they didn't want to have to deal with adding the 
lines together to make the whole text manually).

**Comment by arpitkh96** [comment]
OK I got this. BTW I was looking for a way to make text files as well as databases readable. I have implemented your suggestions in text viewer. I don't think cat can help me read database. What say?
